# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('appName', models.CharField(max_length=50)),
                ('appDesc', models.CharField(max_length=50)),
                ('appHost', models.GenericIPAddressField()),
                ('appDir', models.CharField(max_length=50)),
                ('iisName', models.CharField(max_length=50)),
            ],
        ),
    ]
